export const PostDataDummy = [
  {
    id: "0",
    name: "John",
    userPic: require("../../assets/userImages/user2.jpg"),
    image: require("../../assets/postImages/post1.jpg"),
    isLiked: false,
    isFavourited: false,
    likesCount: "539",
    commentsCount: 2,
    caption: "Best day of my life",
    date: "4 hours ago",
  },
  {
    id: "1",
    name: "Liam",
    userPic: require("../../assets/userImages/default_avatar.jpg"),
    image: require("../../assets/postImages/post2.jpg"),
    isLiked: false,
    isFavourited: false,
    likesCount: "12",
    commentsCount: 1,
    caption: "",
    date: "1 days ago",
  },
  {
    id: "2",
    name: "Oliver",
    userPic: require("../../assets/userImages/user1.jpg"),
    image: require("../../assets/postImages/post1.jpg"),
    isLiked: true,
    isFavourited: false,
    likesCount: "1 232",
    commentsCount: 13,
    caption: "How Beautiful",
    date: "2 days ago",
  },
  {
    id: "3",
    name: "Mark",
    userPic: require("../../assets/userImages/default_avatar.jpg"),
    image: require("../../assets/postImages/post2.jpg"),
    isLiked: true,
    isFavourited: false,
    likesCount: "232",
    commentsCount: 3,
    caption: "Nice",
    date: "2 hours ago",
  },
];
