export const StoryDataDummy = [
  {
    id: "0",
    name: "Saba",
    image: require("../../assets/userImages/owner.png"),
    owner: true,
    hasPostedStory: false,
    hasPostedStoryOnCloseFriends: false,
    hasViewedStory: false,
  },
  {
    id: "1",
    image: require("../../assets/userImages/user1.jpg"),
    name: "Alpha",
    hasPostedStory: true,
    hasPostedStoryOnCloseFriends: false,
    hasViewedStory: false,
  },
  {
    id: "2",
    image: require("../../assets/userImages/user2.jpg"),
    name: "Beta",
    hasPostedStory: true,
    hasPostedStoryOnCloseFriends: true,
    hasViewedStory: false,
  },
  {
    id: "3",
    image: require("../../assets/userImages/user3.jpg"),
    name: "Gamma",
    hasPostedStory: true,
    hasPostedStoryOnCloseFriends: false,
    hasViewedStory: true,
  },
  {
    id: "4",
    image: require("../../assets/userImages/user4.jpg"),
    name: "Delta",
    hasPostedStory: true,
    hasPostedStoryOnCloseFriends: false,
    hasViewedStory: false,
  },
  {
    id: "5",
    image: require("../../assets/userImages/user5.jpg"),
    name: "Epsilon",
    hasPostedStory: true,
    hasPostedStoryOnCloseFriends: true,
    hasViewedStory: true,
  },
  {
    id: "6",
    image: require("../../assets/userImages/user6.jpg"),
    name: "John",
    hasPostedStory: true,
    hasPostedStoryOnCloseFriends: false,
    hasViewedStory: false,
  },
];
